// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sysinfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RamRequest) Reset() {
	*x = RamRequest{}
	mi := &file_proto_sysinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RamRequest) ProtoMessage() {}

func (x *RamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sysinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RamRequest.ProtoReflect.Descriptor instead.
func (*RamRequest) Descriptor() ([]byte, []int) {
	return file_proto_sysinfo_proto_rawDescGZIP(), []int{0}
}

func (x *RamRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

type RamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedPercent   int32                  `protobuf:"varint,1,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RamResponse) Reset() {
	*x = RamResponse{}
	mi := &file_proto_sysinfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RamResponse) ProtoMessage() {}

func (x *RamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sysinfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RamResponse.ProtoReflect.Descriptor instead.
func (*RamResponse) Descriptor() ([]byte, []int) {
	return file_proto_sysinfo_proto_rawDescGZIP(), []int{1}
}

func (x *RamResponse) GetUsedPercent() int32 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *RamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_sysinfo_proto protoreflect.FileDescriptor

const file_proto_sysinfo_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sysinfo.proto\x12\asysinfo\")\n" +
	"\n" +
	"RamRequest\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\"J\n" +
	"\vRamResponse\x12!\n" +
	"\fused_percent\x18\x01 \x01(\x05R\vusedPercent\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2J\n" +
	"\rSystemMonitor\x129\n" +
	"\fGetRamStatus\x12\x13.sysinfo.RamRequest\x1a\x14.sysinfo.RamResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_sysinfo_proto_rawDescOnce sync.Once
	file_proto_sysinfo_proto_rawDescData []byte
)

func file_proto_sysinfo_proto_rawDescGZIP() []byte {
	file_proto_sysinfo_proto_rawDescOnce.Do(func() {
		file_proto_sysinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sysinfo_proto_rawDesc), len(file_proto_sysinfo_proto_rawDesc)))
	})
	return file_proto_sysinfo_proto_rawDescData
}

var file_proto_sysinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sysinfo_proto_goTypes = []any{
	(*RamRequest)(nil),  // 0: sysinfo.RamRequest
	(*RamResponse)(nil), // 1: sysinfo.RamResponse
}
var file_proto_sysinfo_proto_depIdxs = []int32{
	0, // 0: sysinfo.SystemMonitor.GetRamStatus:input_type -> sysinfo.RamRequest
	1, // 1: sysinfo.SystemMonitor.GetRamStatus:output_type -> sysinfo.RamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sysinfo_proto_init() }
func file_proto_sysinfo_proto_init() {
	if File_proto_sysinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sysinfo_proto_rawDesc), len(file_proto_sysinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sysinfo_proto_goTypes,
		DependencyIndexes: file_proto_sysinfo_proto_depIdxs,
		MessageInfos:      file_proto_sysinfo_proto_msgTypes,
	}.Build()
	File_proto_sysinfo_proto = out.File
	file_proto_sysinfo_proto_goTypes = nil
	file_proto_sysinfo_proto_depIdxs = nil
}
