FROM grafana/grafana:11.2.0

# Define un volumen para asegurar la persistencia de los datos de Grafana
VOLUME /var/lib/grafana

# Expone el puerto 3000, que es el puerto predeterminado de la interfaz web de Grafana
EXPOSE 3000
